name: Tests CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint-format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
      - uses: actions/checkout@v4
      - name: Run the linter and check format
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - run: npm run lint
      - run: npm run format:check

  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - run: npm ci
      - run: npm run test
