name: Tests CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          cache: 'npm'
      - run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run formatter checks
        run: npm run format:check

      - name: Run unit tests
        run: npm run test
